import React, { Component } from 'react';
import {WebView, View} from 'react-native';


class Privacidad extends Component{
    render() {
      return (
        <View style={{flex: 1}}>
          <View style={{height: '100%'}}>
            <WebView
              source={{
                html:
                  "<style>p{text-align:justify}</style>" +
                  "<p>" +"YiMi - KIOTRACK S.A. DE C.V (en lo sucesivo denominada como 'YiMi' o la 'Compañía'), una sociedad debidamente constituida conforme las leyes de México. YiMi presta servicios en línea de transporte privado con chofer (en lo sucesivo denominados como los 'Servicios') en la aplicación denominada 'YiMi Conductor' y en los sitios web de YiMi. Se considera como un conductor a los usuarios que navegan en o utilizan los servicios de YiMi Conductor y los sitios web correspondientes de YiMi (en lo sucesivo denominado como el 'Conductor'). Los Usuarios que ingresan navegan o usan las aplicaciones de YiMi Fleet en los sucesivo denominados como 'Socio No Conductor'. Los usuarios que ingresan, navegan o usan las aplicaciones YiMi Pasajero son en lo sucesivo denominados como 'Pasajeros')." +"</p>" +
                  "<p>" +"YiMi presta servicios en línea de transporte privado con chofer (en lo sucesivo denominados como los 'Servicios') en la aplicación denominada 'YiMi Conductor' y en los sitios web de YiMi. Se considera como un Conductor a los usuarios que navegan en o utilizan los servicios de YiMi Conductor y los sitios web correspondientes de YiMi (en los sucesivo denominados como el 'Conductor'). Los usuarios que ingresan, navegan o usan las aplicaciones YiMi Fleet en lo sucesivo son denominados como 'Socio No Conductor' Los Usuarios que ingresan, navegan o usan las aplicaciones de YiMi Pasajero son en lo sucesivo denominados como 'Pasajeros')." +"</p>" +
                  "<p>" +"El presente Aviso de Privacidad de YiMi Conductor (en lo sucesivo denominado como el 'Aviso de privacidad'), conjuntamente con los Términos y condiciones de Uso de YiMi Conductor, establece la base sobre la cual se procesarán todos los datos personales recabados." +"</p>" +
                  "<p>" +"Por favor lea este Aviso de Privacidad para entender las consideraciones y prácticas con relación a los Información Personal (definida más adelante) del Conductor y el tratamiento que se dará a tales datos. Al acceder o navegar en YiMi Conductor, el Conductor por este medio se obliga a aceptar el Aviso de Privacidad." +"</p>" +
                  "<p>" +"Por favor lea este Aviso de Privacidad cuidadosamente, entiéndala y acéptala plenamente antes de utilizar YiMi Conductor. Si el Conductor no está de acuerdo con cualquier punto de este Aviso de Privacidad, debe dejar de utilizar YiMi Conductor inmediatamente. Cuando el Conductor comienza a utilizar la aplicación de YiMi Conductor, el Conductor ha aceptado que YiMi puede recopilar, revelar, almacenar, utilizar, procesar, compartir, transmitir y proteger su información personal (definida más adelante) en cumplimiento con este Aviso de Privacidad." +"</p>" +
                  "<p>" +"1.- Procesamiento de la información Personal" +"</p>" +
                  "<p>" +"YiMi Conductor es propiedad de YiMi y es operada por dicha compañía. YiMi podrá obtener, revelar , utilizar, procesar, almacenar y transmitir la Información Personal del Conductor y procesará y tratará la Información Personal del Conductor de conformidad con este Aviso de Privacidad y la Ley." +"</p>" +
                  "<p>" +"2.- Recopilación de la Información Personal" +"</p>" +
                  "<p>" +"2.1.-  YiMi podrá recopilar Información Personal, incluyendo sin limitación, los siguientes:" +"</p>" +
                  "<p>" +"2.1.1.-  Información Personal" +"</p>" +
                  "<p>" +"El Conductor podrá proporcionar su nombre, número de teléfono móvil, identificación y toda su información Personal relevante de YiMi Conductor, YiMi reconocer la identidad del Conductor y presentará al Conductor o servicios ofrecidos en YiMi Conductor. Si se requiere, el Conductor proporcionará la marca color y modelo del vehículo, la tarjeta de circulación y la documentación oficial del vehículo.YiMi recopila dicha información conforme las leyes y reglamentos para la seguridad personal y de bienes del Conductor. Si el conductor no proporciona dicha información, podría perder el acceso completo a los servicios de YiMi Conductor." +"</p>" +
                  "<p>" +"2.1.2.-  Ubicación" +"</p>" +
                  "<p>" +"YiMi recabará la información de ubicación del Conductor cuando YiMi Conductor se ejecute en primer plano (aplicación abierta y en pantalla) o en segundo plano (aplicación abierta, pero no en pantalla) en el dispositivo del Conductor.. YiMi obtendrá la ubicación del Conductor a través de la dirección relevante (como proporcionar información a YiMi sobre dispositivos cercanos, puntos de acceso a Wi-Fi e información de la estación base) para proveer los Servicios de una mejor manera." +"</p>" +
                  "<p>" +"2.1.3.-  Viaje" +"</p>" +
                  "<p>" +"YiMi recabará la información del lugar de partida y de destino, la localización, la duración y el kilometraje del Conductor. YiMi recopila la información antes mencionada de conformidad con las leyes y reglamentos aplicables, tomando en consideración la protección de la seguridad personal y de la propiedad del Conductor, así como la petición para tratar las disputas del Conductor de conformidad con las reglas de YiMi Conductor." +"</p>" +
                  "<p>" +"2.1.4.-  Información de las llamadas" +"</p>" +
                  "<p>" +"YiMi podrá grabar y recolectar el contenido de las llamadas y mensajes que el conductor realice a través de YiMi Condutor, incluyendo pero no limitando a la duración de las llamadas, el número de teléfono móvil de las partes que se comunican. yiMi mantiene la información antes mencionada a través de la grabación de llamadas, a fin de verificar los hechos y manejar las quejas en caso de disputas o accidentes de seguridad del Conductor." +"</p>" +
                  "<p>" +"2.1.5.-  Estatus de las órdenes y transacciones" +"</p>" +
                  "<p>" +"YiMi registrará las órdenes de servicio del Conductor y el estado de las transacciones. YiMi recopila dicha información de conformidad con las leyes y regulaciones aplicables a efecto de garantizar la seguridad personal y de la propiedad de Conductor, y la solución de disputas." +"</p>" +
                  "<p>" +"2.2.-   Información de calificación" +"</p>" +
                  "<p>" +"El Conductor podrá evaluar al Pasajero de forma anónima en la Plataforma, pero por favor no incluir Información Personal durante dicho proceso, o su información podrá ser transmitida al Pasajero." +"</p>" +
                  "<p>" +"2.3.-   Información Financiera" +"</p>" +
                  "<p>" +"YiMi podrá recabar Información Financiera del Conductor para cobrar y transferir dinero a la cuenta del Conductor, y para cualquier otro propósito relacionado con la prestación de los Servicios." +"</p>" +
                  "<p>" +"2.4.-   Datos Personales Sensibles" +"</p>" +
                  "<p>" +"YiMi podrá solicitar un Certificado de Antecedentes No Penales (expedido por las autoridades competentes) al Conductor, para asegurarse que el Conductor cumple con los requisitos para operar YiMi Conductor. La carga del Certificado de No Antecedentes Penales será considerada como la autorización otorgada por el Conductor a YiMi para recabar, transferir, almacenar y usar dicho certificado de acuerdo con este Aviso de Privacidad." +"</p>" +
                  "<p>" +"2.5.-   Servicio al Cliente" +"</p>" +
                  "<p>" +"Cuando el Conductor contacte al equipo de servicio al cliente de YiMi, YiMi registrará la información de la llamada del Conductor, sus comentarios o sugerencias, el nombre y la información de contacto y otra información proporcionada por el Conductor mediante la grabación de llamadas y en forma de registro manual, de manera que yiMi pueda manejar las disputas, resolver los problemas o dar retroalimentación al Conductor. Si el Conductor se niega a que YiMi recopile dicha información, tal negativa resultará en que el Conductor nuestro equipo de servicio al cliente no pueda atender y resolver las posibles disputas, pero no afectará el uso de las principales funciones comerciales de YiMi Conductor por parte del Conductor." +"</p>" +
                  "<p>" +"2.6.-   Análisis de Datos" +"</p>" +
                  "<p>" +"Para mejorar los servicios de YiMi Conductor YiMi recopilará la información de acceso del Conductor, incluyendo el contenido de búsqueda, dirección IP, el dispositivo (incluyendo modelo del dispositivo, sistema operativo y operador de telecomunicaciones), ubicación, con la finalidad de formar un perfil del Conductor, proporcionando así al Conductor servicios más personalizados y convenientes. YiMi utilizará un mecanismo de almacenamiento en la red del navegador y el almacenamiento en memoria caché de los datos de la aplicación para recabar y almacenar información sobre el dispositivo del Conductor." +"</p>" +
                  "<p>" +"2.7.-  Servicios de Terceros" +"</p>" +
                  "<p>" +"Durante el curso del uso de servicios de terceros por el Conductor, YiMi recopilará (incluyendo la información proporcionada por el Conductor y la información registrada por el sistema) los Datos Personales necesarios del Conductor y la compartirá con el tercero que preste los servicios, de manera que éste pueda proporcionar al Conductor los servicios apropiados. Si el Conductor se niega a que se recopile dicha información, no podrá utilizar los servicios de terceros a través de YiMi Conductor, pero tal negativa no afectará el uso por el Conductor de las principales funciones comerciales de YiMi Conductor." +"</p>" +
                  "<p>" +"3.-  Permisos de Dispositivos" +"</p>" +
                  "<p>" +"3.1.-  YiMi Conductor podrá solicitar algunos permisos en el dispositivo del Conductor. Se considerará que los Socios No Conductores otorgan permisos de acceso a Internet en el dispositivo cuando accedan o utilicen YiMi Conductor." +"</p>" +
                  "<p>" +"3.2.-  El Conductor puede decidir cancelar todos o algunos de los permisos en el dispositivo, para impedir que YiMi recopile los Datos Personales correspondientes. En los distintos dispositivos, la forma para otorgar y cancelar permisos puede ser distinta. Póngase en contacto con los desarrolladores del sistema y del dispositivo para obtener información detallada." +"</p>" +
                  "<p>" +"4.-  Almacenamiento de Datos Personales" +"</p>" +
                  "<p>" +"4.1.-  Periodo de Almacenamiento de Datos Personales" +"</p>" +
                  "<p>" +"4.1.1.-  YiMi mantendrá los Datos Personales del Conductor continuamente mientras éste utilice los servicios de YiMi Conductor." +"</p>" +
                  "<p>" +"4.1.2 .-  A través de la función de configuración de YiMi conductor, no es posible que el Conductor cancele directamente su cuenta. Incluso si el Conductor solicita cancelar su cuenta, YiMi podrá conservar los Datos Personales del Conductor para protección de la seguridad personal y de la propiedad del Conductor, salvo que el Conductor expresamente solicite a YiMi la eliminación de los datos o las leyes y regulaciones aplicables establezcan expresamente lo contrario." +"</p>" +
                  "<p>" +"4.1.3.-  Si el Conductor desea eliminar sus Datos Personales, podrá contactar al área de servicio al cliente de YiMi para presentar la solicitud correspondiente. YiMi eliminará los Datos Personales del Conductor de conformidad con lo establecido por las leyes y reglamentos aplicables." +"</p>" +
                  "<p>" +"4.2 Almacenamiento de Información" +"</p>" +
                  "<p>" +"Los Datos Personales del Conductor recabados por YiMi se transmitirán a y almacenarán en centros de datos en México, los EUA y/o cualquier lugar en cualquier parte del mundo que pertenezca a o que arrienden YiMi y sus filiales de conformidad con la legislación aplicable." +"</p>" +
                  "<p>" +"5.-  Uso de los Datos Personales" +"</p>" +
                  "<p>" +"5.1.-  El Conductor reconoce y acepta que los Datos Personales del Conductor serán utilizados para los fines especificados en el apartado “Recopilación de Datos Personales” anterior." +"</p>" +
                  "<p>" +"5.2.-  El Conductor reconoce y acepta que Los Datos Personales del Conductor pueden ser utilizados en los escenarios de uso que están directa o razonablemente relacionados con los objetivos establecidos en el apartado “Recopilación de Datos Personales”:" +"</p>" +
                  "<p>" +"5.2.1.-  El Conductor reconoce y acepta que YiMi podrá analizar Datos Personales para brindar al Conductor un servicio más personalizado y conveniente." +"</p>" +
                  "<p>" +"5.2.2.-  El Conductor reconoce y acepta que YiMi podrá diseñar, desarrollar y promocionar productos y servicios nuevos basados ​​en las estadísticas de Datos Personales del Conductor." +"</p>" +
                  "<p>" +"5.2.3.-  El Conductor reconoce y acepta que YiMi podrá analizar los Datos Personales del Conductor y compartir dichas estadísticas con el público o un tercero." +"</p>" +
                  "<p>" +"5.2.4.-  El Conductor reconoce y acepta que YiMi enviará al Conductor información y avisos por distintos medios, los cuales pueden incluir, entre otros, el código de verificación requerido para completar los servicios, las notificaciones necesarias relacionadas con los productos o servicios, noticias sobre los servicios de YiMi Conductor, así como actividades de mercadotecnia e información promocional especial, e información promocional de un tercero en cooperación con YiMi Conductor u otro contenido que pueda interesarle al Conductor. Si el Conductor no desea continuar recibiendo la información mencionada, puede darse de baja a través del formato de cancelación de suscripción." +"</p>" +
                  "<p>" +"5.3.-  En el supuesto que YiMi utilice los Datos Personales del Conductor más allá del alcance que está directa o razonablemente relacionado con los objetivos establecidos en el presente Aviso de Privacidad, YiMi lo notificará al Conductor." +"</p>" +
                  "<p>" +"6.-  Intercambio, transferencia y publicidad de los Datos Personales" +"</p>" +
                  "<p>" +"6.1.-  El Conductor reconoce y acepta que YiMi mantendrá la confidencialidad de los Datos Personales del Conductor de conformidad con lo establecido en las leyes y reglamentos aplicables. YiMi no compartirá los Datos Personales del Conductor con otras personas, excepto en las siguientes situaciones:" +"</p>" +
                  "<p>" +"6.1.1.-  El Conductor reconoce y acepta que YiMi podrá compartir los Datos Personales del Conductor para conseguir los intereses comerciales legítimos de sus afiliadas y subsidiarias." +"</p>" +
                  "<p>" +"6.1.2.-  El Conductor reconoce y acepta que YiMi podrá compartir los Datos Personales del Conductor con terceros para prestar servicios a través de YiMi Conductor al Conductor. Por ejemplo, YiMi podrá compartir información con el Socio No Conductor correspondiente o los Pasajeros elegidos por YiMi Conductor, incluyendo el nombre, número de teléfono, y la demás Información Personal que requiera YiMi Conductor." +"</p>" +
                  "<p>" +"6.1.3.-  El Conductor reconoce y acepta que YiMi presta servicios recíprocos a cooperativas externas prestadoras de servicios (en lo sucesivo denominadas como “Cooperativas Externas”). Para mejorar la calidad de los servicios de YiMi, YiMi podrá compartir los Datos Personales del Conductor con sus empresas afiliadas y las Cooperativas Externas." +"</p>" +
                  "<p>" +"6.1.4.-  El Conductor reconoce y acepta que YiMi podrá transferir los Datos Personales del Conductor a vendedores, prestadores de servicios y otros socios que globalmente apoyan los negocios de YiMi, mediante, la prestación de servicios de infraestructura técnica, la prestación de servicios de investigación criminal, el análisis de cómo se utilizan los servicios de YiMi, la evaluación de la efectividad de los servicios, la prestación de servicios al cliente, o facilitando y procesando los pagos. Estos socios se deberán adherir a estrictas obligaciones de confidencialidad afines al presente Aviso de Privacidad y a los contratos que YiMi celebre con ellos." +"</p>" +
                  "<p>" +"6.1.5.-  Cuando el Conductor use servicios de terceros a través de YiMi Conductor, YiMi compartirá los datos personales del Conductor con el tercero que preste dichos servicios." +"</p>" +
                  "<p>" +"6.1.6.-  Con la finalidad de proteger los derechos e intereses legítimos del Conductor, éste reconoce y acepta que, YiMi podrá proporcionar a los interesados la información necesaria para resolver cualquier controversia relacionada con una operación." +"</p>" +
                  "<p>" +"6.1.7.-  El Conductor reconoce y acepta que YiMi podrá revelar los Datos Personales del Conductor a las autoridades administrativas o judiciales de conformidad con las leyes o reglamentos aplicables." +"</p>" +
                  "<p>" +"6.1.8.-  En la medida que lo permitan o requieran las leyes o reglamentos aplicables, se podrán revelar los Datos Personales necesarios del Conductor para proteger el interés público." +"</p>" +
                  "<p>" +"6.1.9.-  Otras situaciones que permita el Conductor." +"</p>" +
                  "<p>" +"6.2.-  YiMi no revelará los Datos Personales del Conductor ningún tercero que no esté contemplado en el presente Aviso de Privacidad, salvo que obtenga el consentimiento del Conductor. YiMi celebrará un acuerdo de confidencialidad estricto con el tercero con el que comparta los Datos Personales del Conductor, solicitándole tomar las medidas de seguridad y confidencialidad necesarias para procesar los Datos Personales del Conductor." +"</p>" +
                  "<p>" +"6.3.-  YiMi mantendrá los Datos Personales del Conductor de manera confidencial de acuerdo con las leyes y reglamentos aplicables. YiMi no revelará públicamente los Datos Personales del Conductor salvo que éste haya previamente otorgado su consentimiento o autorización de manera explícita, o de acuerdo con lo que exija la ley." +"</p>" +
                  "<p>" +"6.4.-  En el caso de una adquisición, fusión, reestructuración y otros cambios, YiMi exigirá a su sucesor que cumpla con el presente Aviso de Privacidad. Si dicho sucesor necesita cambiar la finalidad de uso de los Datos Personales, obtendrá el previo consentimiento explícito del Conductor." +"</p>" +
                  "<p>" +"7.-  Uso de Datos Financieros y Datos Personales Sensibles." +"</p>" +
                  "<p>" +"Para efectos de claridad, no obstante, cualquier cláusula o término en contrario este Aviso de Privacidad, YiMi no transferirá Datos Personales del Conductor a ningún tercero distinto de proveedores de servicios que realicen transferencias de pago o cualquier otro servicio financiero. YiMi no transferirá el Certificado de No Antecedentes Penales u otra Información Personal Sensible del Conductor a ningún tercero. YiMi únicamente recopila, transfiere y almacena Datos Financieros y Personales Sensibles para proveer los Servicios." +"</p>" +
                  "<p>" +"8.-  Derechos de los conductores" +"</p>" +
                  "<p>" +"8.1.-  Acceso" +"</p>" +
                  "<p>" +"El Conductor puede acceder a sus Datos Personales en YiMi Conductor de las siguientes maneras:" +"</p>" +
                  "<p>" +"8.1.1.- Cuenta" +"</p>" +
                  "<p>" +"El Conductor puede acceder a sus Datos Personales y otra información que haya proporcionado a través de su cuenta en YiMi Conductor." +"</p>" +
                  "<p>" +"8.1.2.-  Viaje" +"</p>" +
                  "<p>" +"El conductor puede acceder a los viajes realizados, solicitudes de viaje y estatus de las transacciones en YiMi Conductor." +"</p>" +
                  "<p>" +"8.1.3.-  Monedero" +"</p>" +
                  "<p>" +"El Conductor puede acceder al método de pago, registro de pago y otra información a través de la función de Mi perfil opción Cuenta Bancaria de YiMi Conductor." +"</p>" +
                  "<p>" +"8.2  Rectificación" +"</p>" +
                  "<p>" +"El Conductor tiene derecho a hacer correcciones y actualizaciones de sus Datos Personales. El Conductor podrá corregir o modificar sus Datos Personales en YiMi Conductor presentando una solicitud de corrección al equipo de servicio al cliente de YiMi o de las siguientes maneras:" +"</p>" +
                  "<p>" +"8.2.1.-  Cuenta" +"</p>" +
                  "<p>" +"El Conductor podrá corregir o modificar sus Datos Personales a través de su cuenta en YiMi Conductor." +"</p>" +
                  "<p>" +"8.2.2.-  Configuración" +"</p>" +
                  "<p>" +"El Conductor puede corregir o modificar la contraseña y otra información a través de la función de configuración de YiMi Conductor." +"</p>" +
                  "<p>" +"8.2.3.-  Monedero" +"</p>" +
                  "<p>" +"El Conductor puede corregir o modificar la Información de Pago y otra información a través de la función Mi perfil opción Cuenta Bancaria de YiMi Conductor." +"</p>" +
                  "<p>" +"8.3.-  Oposición" +"</p>" +
                  "<p>" +"8.3.1.-  YiMi protegerá el derecho del Conductor a retirar su consentimiento de las siguientes maneras:" +"</p>" +
                  "<p>" +"- La información comercial enviada por YiMi Conductor indicará al Conductor la manera específica para darse de baja, y el Conductor podrá retirar su consentimiento dándose de baja tal y como se describe en la información comercial." +"</p>" +
                  "<p>" +"- El Conductor podrá retirar a YiMi su autorización para acceder a sus Datos Personales a través de la característica de configuración del dispositivo para cancelar los permisos correspondientes del mismo (incluyendo ubicación, libreta de direcciones, foto, micrófono, cámara, notificación, etc.)." +"</p>" +
                  "<p>" +"- El Conductor también podrá retirar parte de la autorización cancelando la información de la tarjeta bancaria, eliminando información etc." +"</p>" +
                  "<p>" +"8.3.2.-  Cuando el Conductor retire su consentimiento o autorización, YiMi no podrá continuar prestando los servicios correspondientes a la autorización retirada del Conductor. Sin embargo, cuando el Conductor retire su consentimiento o autorización, esto no afectará el procesamiento de los Datos Personales con base en el consentimiento que haya otorgado antes de retirarlo." +"</p>" +
                  "<p>" +"8.4.-  Si el Conductor no puede acceder, rectificar, cancelar, oponerse o eliminar sus Datos Personales y retirar su consentimiento, podrá contactar al equipo de servicio de cliente de YiMi en línea o vía telefónica a través de la función de “servicio al cliente” del teléfono móvil." +"</p>" +
                  "<p>" +"9.-  Cambios" +"</p>" +
                  "<p>" +"9.1.- En caso de que ocurra cualquiera de los siguientes cambios en YiMi Conductor, YiMi hará las modificaciones correspondientes a este Aviso de Privacidad oportunamente:" +"</p>" +
                  "<p>" +"- Cambios de las funciones de negocios de YiMi Conductor." +"</p>" +
                  "<p>" +"- Cambios a las reglas de uso de los Datos Personales del Conductor." +"</p>" +
                  "<p>" +"- Cambios en la información de contacto de YiMi y en sus canales para presentar quejas." +"</p>" +
                  "<p>" +"- Otros cambios que puedan afectar la seguridad de los Datos Personales del Conductor o los derechos de privacidad del Conductor." +"</p>" +
                  "<p>" +"9.2.-  YiMi no limitará los derechos del Conductor conforme a este Aviso de Privacidad sin el consentimiento expreso del Conductor." +"</p>" +
                  "<p>" +"9.3.-  Salvo que se especifique lo contrario, el Aviso de Privacidad modificado entrará en vigor a partir de la fecha de publicación." +"</p>" +
                  "<p>" +"10.-  Definición y Alcance de los Datos Personales" +"</p>" +
                  "<p>" +"10.1.-  Datos Personales se refiere a toda aquella información que permita identificar la identidad de una persona física, por sí o conjuntamente (en lo sucesivo denominada como “Datos Personales”), en su caso, incluye, entre otra información, el nombre, número de teléfono móvil, una copia impresa o escaneada de una identificación u otro documento de identidad, Código Único de Registro de Población ('CURP'), Registro Federal de Contribuyentes ('RFC') o Certificado de Firma Digital o ('CSD'), fotografía, tarjeta de circulación del vehículo, modelo y color del vehículo, póliza de seguro de automóviles, ubicación, pago, registro de retiro de efectivo, número de tarjeta bancaria, información de acceso, contenido de búsqueda, información del dispositivo, operador de telecomunicaciones y IP." +"</p>" +
                  "<p>" +"10.2.-  Datos Personales Sensibles se refiere a aquellos datos personales que afectan la esfera más privada (íntima) de su titular, o cuyo uso indebido podría dar origen a la discriminación e implicar un grave riesgo para éste (en lo sucesivo denominados como “Datos Personales Sensibles”). En el presente Aviso de Privacidad, tales datos incluyen, entre otros, los antecedentes penales y el certificado de No Antecedentes Penales. En caso de ser requerido por las leyes aplicables, YiMi podrá solicitar el consentimiento expreso por escrito del titular de los Datos Personales Sensibles." +"</p>" +
                  "<p>" +"10.3.-  Datos Financieros se refiere a, pero no se limita, a información de tarjeta de crédito o débito o cualquier otro método de pago, cuentas bancarias, registros de facturas, registros de pago, información del buró de crédito, recibo de pagos, datos de identificación fiscal, datos financieros, comprobantes de ingresos, declaraciones de impuestos, y cualquier otra información patrimonial que sea relevante para que YiMi preste los Servicios (en lo sucesivo referidos como “Datos Financieros”, y de manera conjunta con los Datos Personales y los Datos Personales Sensibles se denominará como “Información Personal y/o Datos Personales”)." +"</p>" +
                  "<p>" +"10.4.- Si el Conductor no proporciona alguna de Información Personal que se requiera, se le podrá negar el acceso a todos o parte de los Servicios." +"</p>"
              }}
            />
          </View>
        </View>
      );
    }
  }

  export default Privacidad