import React, { Component } from 'react';
import {WebView, View} from 'react-native';


class Terminos extends Component{
    render() {
      return (
        <View style={{flex: 1}}>
          <View style={{height: '100%'}}>
            <WebView
              source={{
                html:
                  "<style>p{text-align:justify}</style>" +
                  "<p>" +"YiMi y sus filiales prestan servicios en línea de contratación de transporte privado de automóvil (en lo sucesivo denominados como los “Servicios”) en YiMi Conductor y los sitios web de YiMi. Al usuario que acceda, navegue o utilice YiMi Conductor y los sitios web de YiMi, en lo sucesivo se le denominará como el “Conductor”). Al usuario que acceda, navegue o utilice YiMi Fleet y los sitios web de YiMi, en lo sucesivo se le denominará como el “Socio No Conductor”. Los Socios No Conductores podrán conectarse con los Conductores a través del intercambio de información entre YiMi Fleet y YiMi Conductor. Al Conductor que se haya vinculado con un Socio No Conductor (en lo sucesivo se le denominará como “Conductor Vinculado”). Al usuario que acceda, navegue o utilice YiMi Pasajero o los sitios web de YiMi se denominará en lo sucesivo como el “Pasajero”. Al Pasajero que le sea designado al Conductor a través de YiMi Conductor se le denominará en lo sucesivo como el “Pasajero Designado”." +"</p>" +
                  "<p>" +"El Conductor estará sujeto a estos Términos y Condiciones de YiMi Conductor (en lo sucesivo referidos como Términos y Condiciones)." +"</p>" +
                  "<p>" +"No existe relación laboral alguna, directa o indirecta, entre la Compañía y los Conductores. Las leyes y reglamentos tales como la Ley Laboral, Ley del Seguro Social y sus Reglamentos no serán aplicables." +"</p>" +
                  "<p>" +"Al utilizar la cuenta de usuario y contraseña de YiMi Conductor, el Conductor podrá acceder a YiMi Fleet. Sin embargo, el Conductor no podrá disfrutar de todos los servicios de YiMi Fleet hasta que haya cargado todos los documentos e información requerida, que la misma sea aprobada por YiMi y la YiMi Fleet, y que acepte obligarse conforme a todos los Términos y Condiciones de YiMi Fleet." +"</p>" +
                  "<p>" +"Antes de utilizar YiMi Conductor, lea los presentes Términos y Condiciones con atención (especialmente las partes resaltadas en negritas). El Conductor no podrá acceder ni utilizar los Servicios hasta que provea toda la información y documentos requeridos, aprobados por YiMi Conductor y YiMi, y se obligue conforme a estos Términos y Condiciones." +"</p>" +
                  "<p>" +"Si el Conductor elige y utiliza los Servicios, se considerará que el Conductor ha leído y aceptado todos y cada uno de los términos establecidos en el presente documento y acuerda que los presentes Términos y Condiciones son vinculantes para el Conductor y la Compañía. El Conductor observará los siguientes términos en buena fe al utilizar YiMi Conductor." +"</p>" +
                  "<p>" +"Los presentes Términos y Condiciones son aplicables para todos los usuarios o navegadores de la YiMi Conductor, y están sujetos a modificación en cualquier momento como resultado de ajustes a las políticas comerciales. El Conductor debe visitar frecuentemente esta página web y/o la aplicación YiMi Conductor para mantenerse al tanto de los términos que estén vigentes. Las notificaciones, términos u otros requerimientos expresamente especificados o integrados en la página web y/o en YiMi Condutor formarán parte integral de los presentes Términos y Condiciones, ciertas partes de los términos podrán ser sustituidas por los avisos legales, términos o requerimientos más actualizados expresamente especificados o integrados en la página web y/o en YiMi Conductor. Al aceptar los Términos y Condiciones, el Conductor acuerda que también ha leído con atención y aceptado dicho términos sustituidos o referidos. Si el Conductor continúa utilizando los servicios de la Compañía, se considerará que el Conductor ha aceptado los Términos y Condiciones actualizados, de lo contrario, el Conductor dejará de utilizar inmediatamente YiMi Conductor." +"</p>" +
                  "<p>" +"Los presentes Términos y Condiciones dejan expresamente sin efecto cualquier acuerdo o arreglo previo que la Compañía haya celebrado con el Conductor para el uso de YiMi Conductor y de los Servicios. YiMi podrá dar por terminados inmediatamente los presentes Términos y Condiciones o cualquier Servicio con respecto al Conductor, o en general, podrá dejar de ofrecer o negar el acceso a los Servicios o a cualquier parte de los mismos, si YiMi considera que el Conductor ha incurrido en cualquier incumplimiento." +"</p>" +
                  "<p>" +"Asimismo, YiMi se reserva el derecho a negarse a prestar los Servicios al Conductor o negar al Conductor el uso de las páginas web, servicios o aplicaciones de YiMi sin causa alguna." +"</p>" +
                  "<p>" +"1.	Registro del Conductor" +"</p>" +
                  "<p>" +"1.1.- Para utilizar los servicios de contratación de transporte privado en automóvil, el Conductor debe descargar YiMi Conductor, instalarlo en su dispositivo móvil y completar exitosamente el proceso de registro. Al registrarse, el Conductor deberá asegurarse que toda la información que haya proporcionado sea precisa, completa y válida." +"</p>" +
                  "<p>" +"1.2.- El Conductor reconoce y acuerda que una vez que el Conductor sea un usuario registrado de YiMi Conductor, la cuenta de servicio del Conductor se abrirá de forma predeterminada. La cuenta y contraseña predeterminadas serán la cuenta y contraseña de la cuenta de YiMi Conductor del Conductor." +"</p>" +
                  "<p>" +"1.3.- El Conductor deberá tener plena capacidad legal y de ejercicio de conformidad con el Código Civil Federal. Una persona menor de 18 años de edad no podrá ser Conductor." +"</p>" +
                  "<p>" +"2.	Servicios" +"</p>" +
                  "<p>" +"2.1.- Los pasajeros que accedan naveguen o utilicen YiMi Pasajero y los sitios web de YiMi podrán disfrutar los servicios de contratación de transporte privado o compartido en línea con base en sus necesidades de desplazamiento a través de interacción con información fuera de línea y en línea en tiempo real y una efectiva adecuación de recursos fuera de línea a través del análisis de big data. A través de los Servicios, los Pasajeros designados podrán disfrutar de un servicio de transporte privado o compartido prestado por Conductores independientes quienes obtienen información de las solicitudes por medio de YiMi Conductor. Por medio YiMi Conductor, los Conductores pueden disfrutar de los Servicios, incluyendo entre otros, obtener la información de solicitudes de Pasajeros Designados, y adquirir los ingresos debidos de la solicitud a través del servicio de cobranza de tarifas y distribución de YiMi." +"</p>" +
                  "<p>" +"2.2.- Los Conductores prestarán a los Pasajeros Designados servicios de transporte privado o compartido fuera de línea. Antes de aceptar un viaje o después de que el Pasajero o los Pasajeros Designados desciendan del vehículo, el Conductor podrá estar en un periodo de espera-de-viaje, durante el cual la Compañía le proporcionará el servicio de información. Conforme a la interacción de información fuera de línea y en línea en tiempo real y la eficaz adecuación de recursos fuera de línea mediante el análisis de Big Data, YiMi Conductor enviará la información del viaje más adecuado al Conductor. La cooperación entre el Conductor y la Compañía comienza una vez que el Conductor acepte la solicitud por medio de YiMi Conductor y terminará cuando el último Pasajero Designado descienda del vehículo (en lo sucesivo denominado como el “Periodo de Cooperación”. En otros momentos, además del Periodo de Cooperación, la Compañía no exige ni exigirá al Conductor que continúe conduciendo para la Compañía." +"</p>" +
                  "<p>" +"2.3.- El Conductor o el Socio No Conductor podrán subir información relacionada con los vehículos que haya legalmente ocupado o poseído, y que haya registrado en YiMi Fleet (en lo sucesivo denominado como el “Vehículo Registrado”); El Socio No Conductor podrá vincular un Vehículo Registrado con más de un Conductor Vinculado;" +"</p>" +
                  "<p>" +"2.4.- Un Conductor Vinculado podrá vincularse con más de un Vehículo Registrado;" +"</p>" +
                  "<p>" +"2.5.- Cuando un Conductor Vinculado preste servicios de transporte privado o compartido para atender una solicitud en YiMi Conductor, el Conductor Vinculado sólo podrá vincularse con un vehículo." +"</p>" +
                  "<p>" +"2.6.- El Conductor no difundirá ni revelará información personal alguna de Pasajero o Socio No Conductor alguno que haya adquirido al prestar los Servicios a persona alguna, salvo para efectos del Servicio o cuando la haya obtenido legalmente de otras fuentes." +"</p>" +
                  "<p>" +"2.7.- Para utilizar los Servicios, el Conductor deberá presentar a la Compañía cierta información personal. El Conductor se obliga a mantener la información personal que requiera YiMi Conductor en forma precisa, completa y actualizada. Si no cumple con dicha obligación, se podrá impedir al Conductor acceder o utilizar los Servicios." +"</p>" +
                  "<p>" +"3.	Acuerdos y Garantías" +"</p>" +
                  "<p>" +"3.1.- Los Conductores cumplirán con las siguientes normas para la contratación de servicios de transporte privado:" +"</p>" +
                  "<p>" +"-   cumplirán con cualquier requerimiento obligatorio para ser un conductor calificado, establecido por cualquier ley o reglamento aplicable;" +"</p>" +
                  "<p>" +"-   tendrán buen historial de manejo" +"</p>" +
                  "<p>" +"-   hablarán español como hispanoparlante promedio;" +"</p>" +
                  "<p>" +"-   contar con un certificado de no antecedentes penales;" +"</p>" +
                  "<p>" +"-   no tendrán antecedentes de conducir arriesgadamente;" +"</p>" +
                  "<p>" +"-   no tendrán antecedentes de conducir en estado de ebriedad;" +"</p>" +
                  "<p>" +"-   no tendrán antecedentes de drogadicción;" +"</p>" +
                  "<p>" +"-   no tendrán antecedentes de enfermedades que puedan poner en riesgo la seguridad del conductor y de los pasajeros;" +"</p>" +
                  "<p>" +"-   no habrán tenido un accidente de tráfico mayor en los últimos 3 años;" +"</p>" +
                  "<p>" +"-   el entendimiento de lenguas extranjeras es un plus (para conversaciones simples);" +"</p>" +
                  "<p>" +"Las siguientes enfermedades o actos podrían poner en riesgo la seguridad de los pasajeros y del conductor:" +"</p>" +
                  "<p>" +"-   Enfermedad cardiaca orgánica" +"</p>" +
                  "<p>" +"-   Epilepsia" +"</p>" +
                  "<p>" +"-   Síndrome de Meniere" +"</p>" +
                  "<p>" +"-   Vértigo" +"</p>" +
                  "<p>" +"-   Histeria" +"</p>" +
                  "<p>" +"-   Enfermedad de Parkinson" +"</p>" +
                  "<p>" +"-   Psicopatías" +"</p>" +
                  "<p>" +"-   Demencia y enfermedades del sistema nervioso que afecten el uso de las extremidades" +"</p>" +
                  "<p>" +"-   Tomar o inyectarse drogas, tomar fármacos psicotrópicos que crean dependencia por un tiempo prolongado, volverse adicto y no dejarlos;" +"</p>" +
                  "<p>" +"-   Otras enfermedades o enfermedades infecciosas que impidan manejar con seguridad (como tuberculosis, paperas y otras enfermedades infecciosas que se contagien por el aire o por gotículas); y" +"</p>" +
                  "<p>" +"-   Cualquiera otra condición prevista en las leyes y reglamentos nacionales o medidas de implementación locales." +"</p>" +
                  "<p>" +"3.2.-    El Vehículo Registrado cumplirá con los siguientes estándares:" +"</p>" +
                  "<p>" +"-   Los Conductores ocuparán legalmente los Vehículos Registrados;" +"</p>" +
                  "<p>" +"-   El vehículo no habrá estado involucrado en un accidente vial mayor ni haberse inundado nunca;" +"</p>" +
                  "<p>" +"-   El automóvil estará limpio y libre de polvo, sin daños ni rayones aparentes;" +"</p>" +
                  "<p>" +"-   La placa de vehículo debe ser clara;" +"</p>" +
                  "<p>" +"-   Ninguna modificación, ninguna decoración con pintura en aerosol, y no se permiten bocinas de radio manuales;" +"</p>" +
                  "<p>" +"-   Las luces se utilizarán adecuadamente;" +"</p>" +
                  "<p>" +"-   La decoración interior estará limpia y ordenada, sin desgaste ni olores;" +"</p>" +
                  "<p>" +"-   Los asientos estarán limpios y ordenados, libres de desgaste o pliegues;" +"</p>" +
                  "<p>" +"-   Los botones de los instrumentos podrán utilizarse normalmente;" +"</p>" +
                  "<p>" +"-   No calcomanías publicitarias, accesorios, banderines u otros adornos;" +"</p>" +
                  "<p>" +"-   Buena calidad interna, el vehículo está ordenadamente colocado en las posiciones correctas;" +"</p>" +
                  "<p>" +"-   Los vidrios del vehículo contarán con película instalada;" +"</p>" +
                  "<p>" +"-   Los certificados y partes del vehículo estarán completos, en su caso, incluyendo el anuncio del seguro obligatorio, símbolo de protección ambiental verde, marca de inspección del vehículo, licencia de conducir, manual de mantenimiento, juego de herramientas, extintor de incendios, gato, llanta de refacción, encendedor y tapetes;" +"</p>" +
                  "<p>" +"-   Cualquier otro aspecto previsto en las leyes y reglamentos aplicables." +"</p>" +
                  "<p>" +"3.3.- El Conductor no transportará los artículos que le entregue cualquier pasajero por separado si el Pasajero decide no abordar el vehículo." +"</p>" +
                  "<p>" +"3.4.- Es obligación del Conductor mantener el software y hardware de su teléfono móvil actualizado para que adecuarse a los requerimientos de YiMi Conductor. La Compañía no es responsable de cualquier problema que pueda surgir cuando el Conductor use cualquier versión desactualizada de YiMi Conductor y/o use YiMi Conductor en cualquier aparato móvil que no cumpla los requerimientos relevantes de YiMi Conductor. El Conductor acepta que la Compañía puede actualizar los requerimientos del software o hardware del teléfono móvil de YiMi Conductor en cualquier tiempo." +"</p>" +
                  "<p>" +"3.5.- Al usar los Servicios, el Conductor acepta lo siguiente:" +"</p>" +
                  "<p>" +"-   El Conductor usará los Servicio o YiMi Conductor en buena fe;" +"</p>" +
                  "<p>" +"-   El Conductor usará los Servicios o YiMi Conductor solo para uso personal y no revenderá los mismos a cualquier tercero;" +"</p>" +
                  "<p>" +"-   El Conductor no usará los Servicios o YiMi Conductor para propósitos ilegales;" +"</p>" +
                  "<p>" +"-   El Conductor no usará los Servicios o YiMi Conductor para acosar u obstruir o perjudicar a terceros;" +"</p>" +
                  "<p>" +"-   El Conductor no usará los Servicios o YiMi Conductor para afectar la operación normal de la red;" +"</p>" +
                  "<p>" +"-   El Conductor no intentará dañar los Servicios o YiMi Conductor; y" +"</p>" +
                  "<p>" +"-   El Conductor cumplirá con todas las leyes aplicables del país/región, provincia y/o ciudad en la cual el Conductor use los Servicios." +"</p>" +
                  "<p>" +"4.	Servicio y Cuota Cooperación" +"</p>" +
                  "<p>" +"4.1.-   YiMi tiene un mecanismo de precio que se calcula con un algoritmo (en lugar del mecanismo de fijación de precios por kilometraje como se ve generalmente en los servicios de taxi) teniendo en cuenta una tarifa base, el tráfico, el tiempo del viaje y la distancia, así como cualquier otra promoción otorgada por YiMi a su entera discreción." +"</p>" +
                  "<p>" +"4.2.-   El Conductor acuerda que la Compañía podrá liquidarlo(a) periódicamente o extraordinariamente por la cooperación antes mencionada con base en la norma sobre liquidación actualizada de tiempo en tiempo." +"</p>" +
                  "<p>" +"4.3.-   El Conductor Vinculado no podrá retirar ningún saldo de tarifas de su propia cuenta en YiMi Conductor, en cambio, el saldo de las tarifas será exclusivamente controlado por el Socio No Conductor primero, y el Socio No-Conductor podrá distribuir la tarifa de acuerdo con la distribución de la tarifa acordada con el Conductor." +"</p>" +
                  "<p>" +"4.4.-   La tarifa y relación entre el Socio No Conductor y el Conductor Vinculado será acordada, salvo pacto contrario, por el Socio No Conductor y el Conductor Vinculado. YiMi no será responsable por ninguna controversia que resulte por el cobro de tarifas y la relación entre el Conductor Vinculado y el Socio No Conductor." +"</p>" +
                  "<p>" +"4.6.1.- Facturación: El Socio Conductor acepta y reconoce que durante el proceso de registro del Conductor en la aplicación YiMi Conductor, el Conductor proporcionará la información necesaria para determinar la estructura de facturación que será aplicable al Conductor, y los términos y condiciones aplicables." +"</p>" +
                  "<p>" +"4.6.1.1.- Facturación por parte del Conductor:" +"</p>" +
                  "<p>" +"Será aplicable al Conductor que durante el proceso de registro en la aplicación YiMi Conductor proporcionó su información fiscal completa, incluido su Registro Federal de Contribuyente ('RFC') y su Certificado de Firma Digital o ('CSD')." +"</p>" +
                  "<p>" +"YiMi, validará el RFC del Conductor para determinar si el RFC está activo o inactivo. Si el RFC está inactivo, YiMi, a través de la aplicación YiMi Conductor, notificará dicha situación al conductor." +"</p>" +
                  "<p>" +"Si el estado RFC del Conductor está activo y el Conductor proporciona el CSD correspondiente, el Conductor acepta y reconoce los términos del Acuerdo de servicios de facturación, que se está ejecutando entre el Conductor y el Tercero que designe YiMi ('Tercero Autorizado'), según la cual el Tercero Autorizado procesará las facturas en nombre y nombre del Conductor con su CSD y su propio RFC. En este caso, el Conductor está obligado a mantener el CSD válido y renovarlo de acuerdo con las regulaciones fiscales vigentes." +"</p>" +
                  "<p>" +"En el caso de que el CSD del Conductor no se encuentre vigente o no sea válido, el Conductor se obliga a actualizar y proporcionar el nuevo CSD a YiMi, en caso de no actualizarlo, se considerará que el Conductor aceptó cambiar a la opción Facturación en nombre del Conductor por un tercero." +"</p>" +
                  "<p>" +"El Conductor autoriza expresamente a YiMi, a retener los honorarios que se pagarán al Tercero Autorizado por sus servicios de facturación, y a pagar aquellos a nombre del Conductor al Tercero Autorizado." +"</p>" +
                  "<p>" +"4.6.1.2.- Facturación en nombre del Conductor por un tercero:" +"</p>" +
                  "<p>" +"Será aplicable al Conductor que durante el proceso de registro en la aplicación YiMi Conductor no proporcionó su información fiscal completa, ya sea:" +"</p>" +
                  "<p>" +"-   no tienen un Registro Federal de Contribuyentes ('RFC') o Certificado de Firma Digital o 'CSD')" +"</p>" +
                  "<p>" +"-   no ha proporcionado un CSD válido al Tercero Autorizado" +"</p>" +
                  "<p>" +"-   su CSD no se encuentra vigente, o" +"</p>" +
                  "<p>" +"-   no cumple con ningún otro requisito para emitir facturas." +"</p>" +
                  "<p>" +"Para estos casos las siguientes opciones serían aplicables:" +"</p>" +
                  "<p>" +"1) Si el Conductor no cuenta con RFC, o no se lo proporciona a YiMi durante el proceso de registro. En este caso, ya que durante el proceso de registro el Conductor proporcionó su Código Único de Registro de Población ('CURP'), el Conductor acepta expresamente que YiMi o cualquier otro tercero puede y debe registrar al Conductor en el Servicio de Administración Tributaria ('SAT'), usando el CURP del Conductor, para que el Conductor pueda obtener su RFC y, por lo tanto, pueda cumplir con sus obligaciones tributarias en México." +"</p>" +
                  "<p>" +"2) Si el Conductor no proporciona un CSD válido y vigente. En este caso, el Conductor ya tiene un RFC, que se le proporcionó a YiMi, pero no tiene el CSD para emitir facturas." +"</p>" +
                  "<p>" +"Para los dos escenarios anteriores, el Conductor acepta y reconoce su aceptación de los términos de los siguientes acuerdos:" +"</p>" +
                  "<p>" +"-   Contrato de Comisión Comercial, que se está ejecutando entre el Conductor y el emisor de facturas en nombre del Conductor ('Emisor'), según el cual el Emisor actuará como un agente de comisión del Conductor para la emisión de facturas en nombre del Conductor." +"</p>" +
                  "<p>" +"-   Contrato de Servicios de Facturación, que se está ejecutando entre el Conductor y el Tercero Autorizado, según la cual el Tercero Autorizado procesará las facturas en nombre y bajo el nombre del Emisor, que a su vez emitirá las facturas en nombre del Conductor." +"</p>" +
                  "<p>" +"En estos escenarios, el Emisor facturará a los Pasajeros, en nombre y por cuenta del Conductor, en su calidad de agente de comisión comercial, en el entendimiento de que el Tercero Autorizado continuará siendo la parte responsable del procesamiento de las facturas, por lo tanto, el Conductor acepta los términos de ambos acuerdos, el Acuerdo de la Comisión Comercial y el Acuerdo de Servicios de Facturación." +"</p>" +
                  "<p>" +"El Conductor autoriza a YiMi a retener los honorarios que se pagarán a el Emisor y el Tercero Autorizado por sus servicios de facturación y comisiones, y a pagarlos en nombre del Conductor a el Emisor y el Tercero Autorizado." +"</p>" +
                  "<p>" +"El Conductor acepta que YiMi podrá, a su entera discreción, absorber el pago de las tarifas a el Tercero Autorizado y el Emisor en nombre del Conductor, como incentivo. YiMi puede decidir dejar de absorber el pago de esas tarifas en cualquier momento que lo considere conveniente." +"</p>" +
                  "<p>" +"El Conductor está de acuerdo, para todos los fines legales, que YiMi no será parte del Acuerdo de Servicios de Facturación ni del Acuerdo de la Comisión Comercial. En este sentido, la participación de YiMi consiste en permitir que los Conductores acepten los términos del Acuerdo de la Comisión Comercial y el Acuerdo de Servicios de Facturación, al dar a conocer esos términos por solicitud y del Conductor a YiMi. El Tercero Autorizado y el Emisor serán los únicos responsables de sus obligaciones en virtud del Acuerdo de Servicios de Facturación y en virtud del Acuerdo de la Comisión Comercial, y, por lo tanto, YiMi no será responsable ni de ninguna manera responsable por tales obligaciones del Tercero Autorizado o el Emisor." +"</p>" +
                  "<p>" +"4.6.1.3.- Facturación para Conductores existentes:" +"</p>" +
                  "<p>" +"Para el caso de los Conductores existentes que ya operan bajo la aplicación del Conductor YiMi, en cualquier momento a discreción de YiMi, se le puede solicitar a los conductores que proporcionen su información fiscal para cumplir con la cláusula 4.6.1." +"</p>" +
                  "<p>" +"Considerando la información proporcionada por el Conductor, el Conductor acepta y reconoce su aceptación a lo establecido en la cláusula 4.6.1, reconociendo que su registro, o la prestación de servicios bajo la aplicación YiMi Conductor pueden ser cancelados o suspendidos por YiMi si el conductor no proporciona dicha información y/o no acepta los términos de la cláusula 4.6.1." +"</p>" +
                  "<p>" +"4.6.2.- Cargos Adicionales y carreteras de peaje:" +"</p>" +
                  "<p>" +"Según lo establecido en el Acuerdo de servicios de facturación y el Acuerdo de la Comisión comercial establecido en la cláusula 4.6.1., cualquier tarifa de servicio adicional, tarifa, tarifa de reparación o limpieza, o tarifa de carretera de peaje que El Conductor puede incurrir durante la prestación del servicio deberá ser facturado de acuerdo con los acuerdos ejecutados por el Conductor y el Tercero Autorizado y/o el Emisor." +"</p>" +
                  "<p>" +"Con respecto a las tarifas de las carreteras de peaje en esta ley, el Conductor autoriza expresamente a YiMi (i) a pagar en nombre del Conductor las cantidades correspondientes derivadas de las carreteras de peaje de cualquier viaje específico, y (ii) cobrar a los Pasajeros la cantidad de esas carreteras de peaje matrícula." +"</p>" +
                  "<p>" +"4.7.- Los operadores de telecomunicaciones y no YiMi, prestarán y cobrarán los servicios de telecomunicación y cargos relacionados, que se podrán incurrir al utilizar YiMi Conductor." +"</p>" +
                  "<p>" +"5.- Garantía de Servicio" +"</p>" +
                  "<p>" +"5.1.- Cuando el Conductor acepte una solicitud en línea de transporte privado en automóvil o preste servicios al Pasajero Designado, el Conductor será responsable de la calidad del servicio y de la seguridad al manejar de conformidad con las disposiciones de los Términos y Condiciones y las leyes aplicables en su jurisdicción." +"</p>" +
                  "<p>" +"5.2.- En el caso de por culpa de Conductor un tercero sufra cualquier daño o agravio, el Conductor cubrirá la indemnización que corresponda. En caso de que el Conductor sea culpable de cualquier daño o agravio o que su incumplimiento de los presentes Términos y Condiciones cause cualquier pérdida a la Compañía, la Compañía tendrá derecho a reclamar una indemnización al Conductor." +"</p>" +
                  "<p>" +"5.3.- El Conductor reconoce que no existe una relación laboral o subordinada entre el Conductor y YiMi o cualquiera de sus afiliadas, derivada de todas y cada una de las actividades realizadas por el Conductor a las cuales les son aplicables estos Términos y Condiciones, de conformidad con las leyes y reglamentos laborales, de seguridad social y fiscales aplicables en México." +"</p>" +
                  "<p>" +"6.- Responsabilidad del Conductor por incumplimiento" +"</p>" +
                  "<p>" +"6.1.- El Conductor prestará los servicios al Pasajero Designado de conformidad con los estándares de servicio acordados y las leyes aplicables en la jurisdicción del Conductor. Si el Conductor no presta los servicios a los Pasajeros Designados de buena fe (en lo sucesivo denominado como un “Acto Indebido”), incluyendo sin limitación:" +"</p>" +
                  "<p>" +"-   La declaración de cualquier información imprecisa o incompleta;" +"</p>" +
                  "<p>" +"-   Dejar al Pasajero Designado a la mitad del viaje;" +"</p>" +
                  "<p>" +"-   Desviarse intencionalmente;" +"</p>" +
                  "<p>" +"-   Cobrar cuotas ilegalmente;" +"</p>" +
                  "<p>" +"-   Vengarse del Pasajero Designado que se haya quejado de su calidad de servicio o hecho un comentario no satisfactorio sobre su servicio." +"</p>" +
                  "<p>" +"6.2.- Si el Conductor realiza un Acto Indebido, se considerará que el Conductor ha incumplido los presentes Términos y Condiciones, independientemente de que el Pasajero Designado haya presentado una queja o no, y la Compañía tendrá derecho a dar por terminada la cooperación con el Conductor, según requiera el caso. La Compañía tendrá derecho a exigir al Conductor pagar la indemnización completa por la pérdida causada en virtud del Acto Indebido." +"</p>" +
                  "<p>" +"6.3.- Después de aceptar la solicitud, el Conductor no cancelará la solicitud, no se negará a prestar servicios al Pasajero Designado ni incitará ni forzará al Pasajero Designado a cancelar la solicitud (en lo sucesivo denominada como la 'Cancelación después Aceptar una Solicitud'), salvo que el Pasajero Designado ponga en riesgo al Conductor, o la seguridad del vehículo no sea adecuada para prestar los servicios o cualquier otra causa legítima basada en las leyes o reglamentos aplicables en la jurisdicción del Conductor. El Conductor está de acuerdo en que y autoriza a la Compañía a monitorear la información relacionada con la Cancelación después de Aceptar una Solicitud. Una Cancelación después de Aceptar una Solicitud ilegítima será juzgada a la entera discreción de YiMi y se considerará como un incumplimiento de los presentes Términos y Condiciones." +"</p>" +
                  "<p>" +"6.4.- Si el Conductor incumple cualquier contrato que haya celebrado con YiMi o sus filiales, la Compañía podrá, a su entera discreción, dar por terminados los presentes Términos y Condiciones con el Conductor según requiera el caso." +"</p>" +
                  "<p>" +"6.5.- El Conductor se obliga a indemnizar a la Compañía y a los funcionarios, consejeros y empleados de la Compañía inmediatamente que se le requiera, por todas las reclamaciones, responsabilidades, daños, costos y gastos, incluyendo honorarios de abogados, derivados de cualquier incumplimiento de los presentes Términos y Condiciones celebrados por el Conductor y YiMi o cualesquier otras responsabilidades derivadas del uso de YiMi Conductor por parte del Conductor." +"</p>" +
                  "<p>" +"6.6.- Si el Vehículo Registrado operativo no coincide con la información registrada, incluyendo placas falsas, póliza de seguro no válida, marca de vehículo falsa, el Conductor pagará a YiMi una multa de MXN $1,500 (mil quinientos pesos) y YiMi, mientras tanto, tendrá derecho a dar el contrato con el Conductor por terminado y dejar de prestar servicios permanentemente para el Conductor" +"</p>" +
                  "<p>" +"6.7.- La Compañía tendrá derecho a cobrar a la parte responsable cualquier cantidad que supere el monto de la indemnización que corresponda conforme a la ley, así como a tomar medidas en contra de las partes incumplidas o infractoras." +"</p>" +
                  "<p>" +"7.- Responsabilidad por Engaño o Fraude" +"</p>" +
                  "<p>" +"Cualquier conducta para obtener concesiones, recompensas u otros beneficios a través de cualquier forma de comportamiento engañoso o reventa puede violar las leyes y reglamentos aplicables, y la Compañía resistirá o boicoteará severamente tales conductas conforme a las leyes y reglamentos aplicables. El Conductor asumirá las responsabilidades de dichas conductas engañosas o de fraude, y dicha conducta se considera como un incumplimiento de los presentes Términos y Condiciones. Asimismo, la Compañía se reserva el derecho de presentar una demanda." +"</p>" +
                  "<p>" +"8.- Suspensión y Terminación" +"</p>" +
                  "<p>" +"1. La Compañía determinará, a su entera discreción, si ha ocurrido un incumplimiento de los presentes Términos y Condiciones en virtud del uso de YiMi Conductor por parte del Conductor. Cuando haya ocurrido un incumplimiento de estos Términos y Condiciones, la Compañía podrá tomar las medidas que considere adecuadas." +"</p>" +
                  "<p>" +"2. Un incumplimiento de los presentes Términos y Condiciones podrá resultar en las siguientes medidas:" +"</p>" +
                  "<p>" +"-   En una advertencia;" +"</p>" +
                  "<p>" +"-   Declaración de información relevante a las autoridades;" +"</p>" +
                  "<p>" +"-   Suspensión y/o retiro inmediato, temporal o permanente del derecho del Conductor de utilizar YiMi Conductor;" +"</p>" +
                  "<p>" +"-   Acciones legales y demandas en contra del Conductor para obtener el reembolso todos los costos sobre una base de indemnización (incluyendo, sin limitación, costos razonables administrativos y de abogados) que resulten del incumplimiento; o" +"</p>" +
                  "<p>" +"-   Acciones legales adicionales en contra del Conductor." +"</p>" +
                  "<p>" +"9.- Restricciones Regulatorias Locales" +"</p>" +
                  "<p>" +"YiMi Conductor no está dirigida a persona alguna en cualquier jurisdicción en la que (debido a la nacionalidad, residencia u otro motivo) el acceso a o disponibilidad de YiMi Conductor esté prohibido o estaría sujeto a cualquier restricción, incluyendo requerimientos de registro u otros requerimientos dentro de dicha jurisdicción. YiMi se reserva el derecho de limitar el acceso al YiMi Conductor a cualquiera de estas personas. Las personas que accedan a YiMi Conductor lo hacen por iniciativa propia y serán responsables de cumplir con las leyes y reglamentos locales aplicables. YiMi no será responsable frente a ningún usuario por pérdida o daño alguno, ya sea conforme una disposición contractual, por responsabilidad civil (incluyendo negligencia), incumplimiento de un deber conforme a la ley o por otro motivo, aun cuando sea previsible, derivado de o relacionado con el uso por una persona en una jurisdicción donde el acceso a la disponibilidad de YiMi Conductor esté prohibido o sujeto cualquier restricción. En caso de duda, el Conductor deberá obtener asesoría legal independiente." +"</p>" +
                  "<p>" +"10.- Ausencia de Garantías" +"</p>" +
                  "<p>" +"10.1.- YiMi Conductor se ofrece 'en el estado en que se encuentra' y no se otorga garantía alguna, ni expresa ni implícita, con respecto al YiMi Conductor." +"</p>" +
                  "<p>" +"10.2.- Salvo por lo expresamente establecido en los presentes Términos y Condiciones, todas las garantías, condiciones y declaraciones, expresas o implícitas por ley o de otra manera indicadas por YiMi (incluyendo, sin limitación, garantías en cuanto a calidad satisfactoria, idoneidad para un fin o pericia y cuidado) quedan excluidas por esta disposición cuando la ley lo permita." +"</p>" +
                  "<p>" +"11.- Limitación de la Responsabilidad de YiMi" +"</p>" +
                  "<p>" +"11.1.- La información proporcionada y los Servicios recomendados al Conductor en los sitios web de YiMi o en YiMi Conductor son únicamente para referencia del Conductor. YiMi hará esfuerzos razonables para garantizar la precisión de dicha información, en el entendido, no obstante, que YiMi no garantiza que dicha información esté libre de cualquier error, defecto, software malicioso o virus." +"</p>" +
                  "<p>" +"11.2.- YiMi no será responsable por daño alguno que resulte del uso del (o cualquier imposibilidad de usar el) sitio web de YiMi o YiMi Conductor. Asimismo, YiMi no será responsable por daño alguno que resulte del uso de (o cualquier imposibilidad de usar) las herramientas de comunicación electrónica de los sitios web de YiMi o YiMi Conducto, incluyendo, sin limitación, daños causados por fallas de transmisión, mal funcionamiento de Internet o retraso en las comunicaciones electrónicas, intercepción o manipulación de comunicaciones electrónicas por un tercero o programas de cómputo utilizados para la comunicación electrónica y transmisión del virus, falta de energía, huelgas u otras disputas laborales, disturbios, insurrecciones, revueltas, terremotos, incendios, inundación, tormentas, explosiones, guerras; actos del gobierno, órdenes de autoridades judiciales o administrativas o cualquier otra causa de fuerza mayor u omisión de terceros." +"</p>" +
                  "<p>" +"11.3.- YiMi no será responsable por daños indirectos, emergentes, especiales, ejemplares, punitivos o incidentales, incluyendo pérdida de utilidades, pérdida de información, lesiones o daños materiales relacionados con o que de otra manera resulten de cualquier uso de los Servicios, independientemente de la negligencia (que sea activa, afirmativa, única o concurrente) de YiMi, aún si YiMi ha sido advertida de la posibilidad de tales daños." +"</p>" +
                  "<p>" +"11.4.- YiMi no asume responsabilidad alguna con respecto a la precisión, integridad suficiencia y confiabilidad de la información y contenido incluido en YiMi Conductor o en los sitios web de YiMi, incluyendo sin limitación textos, imágenes, datos, opiniones, páginas web o enlaces, a pesar de sus esfuerzos de proporcionar información precisa y exhaustiva en la medida posible. YiMi se deslinda de cualquier responsabilidad por cualquier error u omisión y no otorga garantía expresa o implícita alguna." +"</p>" +
                  "<p>" +"12.- Autorización y Licencia" +"</p>" +
                  "<p>" +"12.1.-	Sujeto al cumplimiento por parte del Conductor con los presentes Términos y Condiciones, YiMi otorga al Conductor una licencia limitada, no exclusiva y no transferible para descargar e instalar una copia de las aplicaciones en un solo dispositivo móvil que el Conductor posea o controle para utilizar dicha copia de las aplicaciones únicamente para el uso personal del propio Conductor." +"</p>" +
                  "<p>" +"12.2.-	El Conductor no podrá: (1) otorgar licencias o sub-licencias, vender, revender, transmitir, ceder, distribuir o de otra manera explotar comercialmente o poner a disposición de terceros los servicios o aplicaciones en forma alguna; (2) modificar o crear obras derivadas basadas en los Servicios o las aplicaciones; (3) crear “enlaces” de Internet a los Servicios, o “enmarcar” o “reproducir” cualquier aplicación en cualquier otro servidor o dispositivo inalámbrico o basado en el Internet; (4) llevar a cabo ingeniería de reversa o acceder a las aplicaciones con el fin de diseñar o crear un producto o Servicio competitivo, diseñar o crear un producto utilizando ideas o gráficos similares a los Servicios o las aplicaciones, o copiar cualesquier ideas, características, funciones o gráficos de los Servicios o las aplicaciones; o (5) lanzar un programa o script automatizado, o cualquier programa que pueda hacer múltiples solicitudes a servidores por segundo, o que dificulte u obstaculice indebidamente la operación y/o desempeño de los Servicios o las aplicaciones." +"</p>" +
                  "<p>" +"12.3.-	Asimismo, el Conductor no deberá: (1) enviar spam o mensajes duplicados o no solicitados en violación de las leyes aplicables; (2) enviar o almacenar material violatorio, obsceno, amenazante, difamatorio o que de otra manera sea ilegal o ilícito, incluyendo material que infrinja los derechos de privacidad de terceros; (3) enviar o almacenar material que contenga virus de software, gusanos, caballos troyanos u otro código informático, archivos, scripts, agentes o programas perjudiciales; (4) interferir con o afectar la integridad o el funcionamiento de los sitios web de YiMi, sus aplicaciones o los Servicios o los datos contenidos en los mismo; ni (5) intentar obtener acceso no autorizado al sitio web de YiMi, sus aplicaciones, los Servicios o sistemas o redes relacionados." +"</p>" +
                  "<p>" +"12.4.- YiMi tendrá derecho a investigar y promover un juicio por cualquiera de los incumplimientos antes mencionados en la mayor medida permitida por la ley. YiMi podrá participar en y asistir a las autoridades encargadas del orden público en las demandas en contra de cualquier Conductor que haya incumplido los presentes Términos y Condiciones. Si YiMi determina que cualquier contenido infringe los presentes Términos y Condiciones o de otra manera perjudica al sitio web de YiMi, YiMi Conductor y/o los Servicios o aplicaciones relacionados, YiMi se reserva el derecho de eliminar o prohibir el acceso a dicho contenido en cualquier momento sin previa notificación" +"</p>" +
                  "<p>" +"13.- Política de Propiedad Intelectual" +"</p>" +
                  "<p>" +"13.1.-	YiMi y sus filiales son titulares de los derechos de propiedad intelectual de todo el contenido distribuido en YiMi Conductor, incluyendo, sin limitación, el software proporcionado y los productos o servicios relacionados, y tales derechos de propiedad intelectual están protegidos por las leyes. La falta de una declaración de titularidad en cierto contenido no implica que YiMi no tenga la titularidad del mismo o no pueda hacer valer sus derechos sobre el mismo y el Conductor respetará los legítimos derechos e intereses del titular y utilizará dicho contenido legalmente de conformidad con las leyes y reglamentos aplicables y el principio de buena fe." +"</p>" +
                  "<p>" +"13.2.-	Sin el consentimiento por escrito de YiMi, ninguna persona física o moral utilizará, copiará, modificará, hará extractos de, incluirá con otros productos para su uso o venta, vinculará ni transmitirá vía un híper-vínculo, almacenará en un sistema de recuperación de información ni utilizará para ningún otro fin comercial cualquier parte del software, de los productos o servicios, de la información o las palabras antes mencionadas en forma alguna bajo ninguna circunstancia, excepto para la descarga o impresión para uso personal no comercial, en el entendido de que no se realizará modificación alguna a lo anterior, y que la declaración de derechos de autor u otra titularidad contenida en los mismos se conservará." +"</p>" +
                  "<p>" +"13.3.-	Las marcas registradas y logotipos (en lo sucesivo conjuntamente denominados como “Marcas Comerciales”) utilizadas y mostradas en dicho software constituirán las Marcas Comerciales, registradas o no registradas, de YiMi y sus filiales en la industria de contratación de servicios de transporte privado y otros campos relacionados, mismas que están protegidas por las leyes. Ninguna persona utilizará contenido alguno de dicho software, “YiMi y nombres similares, así como las Marcas Comerciales en forma alguna sin el consentimiento por escrito de YiMi." +"</p>" +
                  "<p>" +"13.4.-	Si el Conductor imprime, copia, descarga, modifica o vincula cualquier parte del Contenido disponible a través de la página web o la aplicación, en incumplimiento de los presentes Términos y Condiciones, el derecho del Conductor de utilizar los Sitios Web de la Compañía y la aplicación podrán suspenderse inmediatamente y el Conductor deberá, a discreción de la Compañía, devolver o destruir cualesquier copias (electrónicas o en otro formato) de los materiales que haya realizado." +"</p>" +
                  "<p>" +"14.- Servicios y Enlaces a Terceros" +"</p>" +
                  "<p>" +"14.1.-	Durante el uso de las páginas web y aplicaciones relevantes, YiMi podrá, de tiempo en tiempo, proporcionar al Conductor enlaces a sitios web propiedad de y controlados por terceros, para facilitar la comunicación del Pasajero con, la compra de productos o servicios a o para participar en actividades promocionales ofertadas por dichos terceros. Al hacer clic en dichos enlaces links, el Conductor abandonará el sitio web de YiMi o YiMi Conductor y visitará sitios web alojados por dichos terceros que están fuera del control de YiMi, y donde dichos terceros han elaborado sus propios términos, condiciones y políticas de privacidad. Por lo tanto, YiMi no será responsable del contenido y las actividades de dichas páginas web y YiMi no asumirá obligación alguna al respecto. El Conductor entenderá plenamente el contenido y las actividades de dichos sitios web y asumirá plenamente la responsabilidad legal y los riesgos derivados de la navegación o acceso a dichos sitios web por parte del Pasajero." +"</p>" +
                  "<p>" +"15.- Término" +"</p>" +
                  "<p>" +"15.1.-  Los presentes Términos y Condiciones acordados por el Conductor y YiMi no tendrán un término de vigencia establecido." +"</p>" +
                  "<p>" +"15.2.-  Si el Conductor comete cualquiera de los siguientes actos, YiMi tendrá derecho a dar los presentes Términos y Condiciones por terminados en cualquier momento, con efectos inmediatos (es decir, el Conductor tendrá prohibido utilizar YiMi Conductor y los Servicios):" +"</p>" +
                  "<p>" +"-   si el Conductor viola o incumple cualquier término de los presentes Términos y Condiciones;" +"</p>" +
                  "<p>" +"-   a la entera discreción de YiMi, si el Conductor abusa YiMi Conductor, los Servicios o los Sitios Web de YiMi." +"</p>" +
                  "<p>" +"15.3.-  Aunque YiMi de por terminado los presentes Términos y Condiciones, el Conductor será responsable de cualquier daño o perjuicio que pueda derivar de dicho incumplimiento." +"</p>" +
                  "<p>" +"15.4.-  YiMi no estará obligada a notificar la terminación de los Términos y Condiciones con anticipación. Después de la terminación, YiMi enviará la notificación respectiva de conformidad con los presentes Términos y Condiciones." +"</p>" +
                  "<p>" +"16.- Fuerza Mayor" +"</p>" +
                  "<p>" +"En caso de que se presente una fuerza mayor, la parte afectada podrá suspender temporalmente el cumplimiento de sus obligaciones conforme al presente instrumento hasta que el efecto de dicha causa de fuerza mayor cese, y no incurrirá en incumplimiento de contrato; en el entendido, no obstante que dicha parte hará su mejor esfuerzo para resolver dicha causa y mitigar las pérdidas. Fuerza mayor significa cualquier causa impredecible e inevitable (aun cuando sea previsible) fuera del control de las partes que impida, afecte o demore el cumplimiento por una parte de todas o cualquiera de sus obligaciones conforme al presente instrumento. Dichas causas incluyen, sin limitación, terremotos, guerra, modificación de las leyes reglamentos y políticas gubernamentales, virus de cómputo, ataques de hackers o suspensión de servicios prestados por empresas de telecomunicación." +"</p>" +
                  "<p>" +"17.- Disposiciones Generales" +"</p>" +
                  "<p>" +"17.1.- Si se declara la nulidad de ciertos términos de los presentes Términos y Condiciones, pero los demás términos pueden seguir siendo válidos y su exigibilidad no se ve afectada, YiMi determinará si continuará cumpliendo o no con tales otros términos." +"</p>" +
                  "<p>" +"17.2.- YiMi podrá entregar una notificación publicando una notificación general en su sitio web y/o en YiMi Conductor o enviando un correo electrónico o mensaje de texto a la dirección de correo electrónico o número de teléfono móvil registrado en la información de la cuenta del Conductor. Las notificaciones, que podrán publicarse de tiempo en tiempo, constituirán parte de los presentes Términos y Condiciones." +"</p>" +
                  "<p>" +"17.3.- El Conductor no cederá ninguno de los derechos conforme a los presentes Términos y Condiciones sin el previo consentimiento por escrito de YiMi." +"</p>" +
                  "<p>" +"18.- Otros Términos Aplicables" +"</p>" +
                  "<p>" +"Los presentes Términos y Condiciones hacen referencia a los siguientes términos adicionales, los cuales también serán aplicables al uso de los sitios web, contenido, productos, Servicios y aplicaciones de la Compañía por el Conductor, mismos que, debido al uso, el Conductor se obliga a cumplir:" +"</p>" +
                  "<p>" +"18.1.- El Aviso de Privacidad de YiMi Conductor que establece los términos conforme a los cuales se procesan cualesquier datos personales o informaciones recopilados o proporcionados por el Conductor" +"</p>" +
                  "<p>" +"19.- Ley Aplicable" +"</p>" +
                  "<p>" +"Los presentes Términos y Condiciones se regirán por las leyes aplicables en México. Cualquier conflicto, reclamación o controversia derivada de o relacionada con el incumplimiento, terminación, cumplimiento, interpretación o validez de los presentes Términos y Condiciones o el uso del sitio web de YiMi o de YiMi Conductor, se someterá a la jurisdicción de un tribunal competente de la Ciudad de México, México y el Conductor en este acto expresa e irrevocablemente renuncia a cualquier otra jurisdicción que pueda corresponderle en virtud de sus domicilios presentes o futuros." +"</p>" +
                  "<p>" +"20.- Subsistencia" +"</p>" + 
                  "<p>" +"Aún y cuando los presentes Términos y Condiciones se den por terminados o anulen, las disposiciones relacionadas con la obligación de confidencialidad del Conductor, leyes y jurisdicción aplicables subsistirán." +"</p>"
              }}
            />
          </View>
        </View>
      );
    }
  }

  export default Terminos;
